-- AlterTable
ALTER TABLE `bbaapplication` MODIFY `fullName` VARCHAR(255) NULL,
    MODIFY `gender` VARCHAR(20) NULL,
    MODIFY `dateOfBirth` VARCHAR(50) NULL,
    MODIFY `category` VARCHAR(50) NULL,
    MODIFY `nationality` VARCHAR(50) NULL,
    MODIFY `aadhaarNumber` VARCHAR(20) NULL,
    MODIFY `mobileNumber` VARCHAR(15) NULL,
    MODIFY `email` VARCHAR(255) NULL,
    MODIFY `permanentAddress` TEXT NULL,
    MODIFY `corrAddressLine` VARCHAR(255) NULL,
    MODIFY `corrState` VARCHAR(100) NULL,
    MODIFY `corrDistrict` VARCHAR(100) NULL,
    MODIFY `corrPinCode` VARCHAR(10) NULL,
    MODIFY `fatherName` VARCHAR(191) NULL,
    MODIFY `fatherMobile` VARCHAR(191) NULL,
    MODIFY `fatherOccupation` VARCHAR(191) NULL,
    MODIFY `fatherIncome` VARCHAR(191) NULL,
    MODIFY `motherName` VARCHAR(191) NULL,
    MODIFY `motherMobile` VARCHAR(191) NULL,
    MODIFY `motherOccupation` VARCHAR(191) NULL,
    MODIFY `motherIncome` VARCHAR(191) NULL,
    MODIFY `guardianName` VARCHAR(191) NULL,
    MODIFY `guardianRelation` VARCHAR(191) NULL,
    MODIFY `guardianMobile` VARCHAR(191) NULL,
    MODIFY `guardianAddress` TEXT NULL,
    MODIFY `c10Board` VARCHAR(191) NULL,
    MODIFY `c10School` VARCHAR(191) NULL,
    MODIFY `c10Year` VARCHAR(191) NULL,
    MODIFY `c10MaxMarks` VARCHAR(191) NULL,
    MODIFY `c10MarksObt` VARCHAR(191) NULL,
    MODIFY `c10Percentage` VARCHAR(191) NULL,
    MODIFY `c12Board` VARCHAR(191) NULL,
    MODIFY `c12School` VARCHAR(191) NULL,
    MODIFY `c12Year` VARCHAR(191) NULL,
    MODIFY `c12MaxMarks` VARCHAR(191) NULL,
    MODIFY `c12MarksObt` VARCHAR(191) NULL,
    MODIFY `c12Percentage` VARCHAR(191) NULL,
    MODIFY `passed10Plus2` VARCHAR(191) NULL DEFAULT 'No',
    MODIFY `hostelRequired` VARCHAR(191) NULL DEFAULT 'No',
    MODIFY `guardianConsent` VARCHAR(191) NULL DEFAULT 'No',
    MODIFY `declaration` VARCHAR(191) NULL DEFAULT 'false';

-- AlterTable
ALTER TABLE `mbaapplication` MODIFY `firstName` VARCHAR(100) NULL,
    MODIFY `lastName` VARCHAR(100) NULL,
    MODIFY `gender` VARCHAR(20) NULL,
    MODIFY `dateOfBirth` VARCHAR(50) NULL,
    MODIFY `bloodGroup` VARCHAR(10) NULL,
    MODIFY `category` VARCHAR(50) NULL,
    MODIFY `aadhaarNumber` VARCHAR(20) NULL,
    MODIFY `panNumber` VARCHAR(20) NULL,
    MODIFY `mobileNumber` VARCHAR(15) NULL,
    MODIFY `permAddressLine1` VARCHAR(255) NULL,
    MODIFY `permCity` VARCHAR(100) NULL,
    MODIFY `permDistrict` VARCHAR(100) NULL,
    MODIFY `permState` VARCHAR(100) NULL,
    MODIFY `permPinCode` VARCHAR(10) NULL,
    MODIFY `degree` VARCHAR(191) NULL,
    MODIFY `specialisation` VARCHAR(191) NULL,
    MODIFY `c10Board` VARCHAR(191) NULL,
    MODIFY `c10Inst` VARCHAR(191) NULL,
    MODIFY `c10Year` VARCHAR(191) NULL,
    MODIFY `c10Marks` VARCHAR(191) NULL,
    MODIFY `c12Board` VARCHAR(191) NULL,
    MODIFY `c12Inst` VARCHAR(191) NULL,
    MODIFY `c12Year` VARCHAR(191) NULL,
    MODIFY `c12Marks` VARCHAR(191) NULL,
    MODIFY `gradBoard` VARCHAR(191) NULL,
    MODIFY `gradInst` VARCHAR(191) NULL,
    MODIFY `gradYear` VARCHAR(191) NULL,
    MODIFY `gradMarks` VARCHAR(191) NULL,
    MODIFY `hasWorkExp` VARCHAR(191) NULL DEFAULT 'no',
    MODIFY `declaration` VARCHAR(191) NULL DEFAULT 'false';
